server:
  port: -1

spring:
  application:
    name: ad-export
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad-data?autoReconnect=true
    username: ad-user
    password: adPassword123
    tomcat:
      max-active: 4
      min-idle: 1
      initial-size: 2
